"use client";
import { Provider } from "react-redux";
import "./globals.css";
import store from "@/store";

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <title>To-Do App</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;500;700&display=swap"
          rel="stylesheet"
        />
      </head>
      <body>
        <Provider store={store}>
          <main>{children}</main>
        </Provider>
      </body>
    </html>
  );
}
